CREATE TABLE ROOM(
ROOMID NUMBER GENERATED ALWAYS as IDENTITY(START with 1000 INCREMENT by 1),
NAME NVARCHAR2(200),
AREA NUMBER(10,1),
LOCATION VARCHAR2(200),
PRICE NUMBER,
DESCRIPTION NVARCHAR2(200),
STATUS NVARCHAR2(10),
CATEGORYID NUMBER,
LANDLORDCONTRACTID NUMBER,
VOTE NUMBER(1),
ISALLOWMATCH NVARCHAR2(10)
);

CREATE TABLE ROOMCATEGORYDETAIL(
CATEGORYID NUMBER,
MAXPEOPLE NUMBER(2)
);
CREATE TABLE REVIEWROOM(
ROOMID NUMBER,
CUSTOMERID NUMBER,
REVIEW NVARCHAR2(200),
VOTE NUMBER(1)
);

CREATE TABLE ACCOUNT(
PHONE VARCHAR2(10),
NAME NVARCHAR2(50),
ROLE NVARCHAR2(40),
EMAIL VARCHAR2(64),
PASSWORD VARCHAR2(20)
);

CREATE TABLE CUSTOMER(
CCCD NUMBER,
NAME NVARCHAR2(50),
PHONE VARCHAR2(10),
GENDER VARCHAR2(10),
BIRTHDAY DATE,
BANKACCOUNT VARCHAR2(15),
RELATIVENAME NVARCHAR2(200),
RELATIVEPHONE VARCHAR(10),
ROOMIDMATCH NUMBER
);
CREATE TABLE LANDLORD(
CCCD NUMBER,
NAME NVARCHAR2(50),
PHONE VARCHAR2(10),
BANKACCOUNT VARCHAR2(15)
);
CREATE TABLE CONTRACT (
CONTRACTID NUMBER GENERATED ALWAYS as IDENTITY(START with 10000 INCREMENT by 1),
CUSTOMER_ID NUMBER,
CUSTOMER_NAME NVARCHAR2(50),
ROOM_ID NUMBER,
DURATION NUMBER(2),
PRICE NUMBER,
SIGN_DATE DATE,
STATUS NVARCHAR2(30),
ELECTRICPRICE NUMBER,
WATERPRICE NUMBER, 
ENTER_DATE DATE,
CANCEL_DATE DATE,
DEPOSIT NUMBER,
NUMBEROFPEOPLE NUMBER(2)
);

CREATE TABLE CONTRACT_LANDLORD (
CONTRACTID NUMBER GENERATED ALWAYS as IDENTITY(START with 100001 INCREMENT by 1),
LANDLORDID NUMBER,
SIGNED_DATE DATE,
STATUS VARCHAR2(100),
DURATION NUMBER(2)
);

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID NUMBER,
ROLE NVARCHAR2(40),
NAME NVARCHAR2(5)
);

CREATE TABLE RESIDENT_REGISTRATION(
CCCD NUMBER,
PERMANENT_RESIDENT NVARCHAR2(100),
TEMPORARY_ACCOMMODATION NVARCHAR2(100),
CURRENT_RESIDENT NVARCHAR2(100),
CURRENT_WORK NVARCHAR2(50)
);

CREATE TABLE BILL (
BILL_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 10 INCREMENT by 1),
CUSTOMER_ID NUMBER,
DATE_CREATED DATE,
PAY_DATE DATE,
STATUS NVARCHAR2(20)
);

CREATE TABLE BILL_CUSTOMER(
BILL_ID NUMBER,
ROOMID NUMBER,
WATER NUMBER(10),
ELECTRIC NUMBER(10),
WIFI NUMBER(10),
GARBAGE NUMBER(10),
PRICE NUMBER
);
drop table bill_customer;
CREATE TABLE BILL_LANDLORD(
BILL_ID NUMBER,
CONTRACT_ID NUMBER,
PRICE NUMBER);

CREATE TABLE ROOMSERVICE(
SERVICE_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
ROOM_ID NUMBER,
DESCRIPTION NVARCHAR2(200),
PRICE NUMBER,
CREATED_DATE DATE,
STATUS NVARCHAR2(30)
);

CREATE TABLE REPORTCUSTOMER(
ROOMID NUMBER,
FROM_CUSTOMER NUMBER,
REPORTCONTENT NVARCHAR2(200),
ISSOLVE VARCHAR2(10)
);
DROP TABLE REPORTCUSTOMER;
CREATE TABLE CCCDIMAGE (
CCCD NUMBER,
PATH VARCHAR2(200)
);
CREATE TABLE CUSTOMER_LANDLORD_PROFILE 
(
 CCCD NUMBER,
 PATH VARCHAR2(200)
);

CREATE TABLE ROOMIMAGE(
ROOMID NUMBER,
PATH VARCHAR2(200)
);

INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH)  VALUES('NHï¿½ M?T PH?',40,'???NNG TR?N H?NG ??O,PH??NG 2,QU?NN 3,HCMC',2500000,'NHï¿½ R?NG,M?T PH? GIï¿½P 2 CON ???NG','TR?NG',100,100001,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('NHï¿½ SIï¿½U ??P',40,'???NG Vï¿½ TH? Sï¿½U ,PH??NNG 4,QUï¿½N 5,HCMC',1500000,'NHï¿½ Rï¿½NG, M?T PH? GIï¿½P 2 CON ???NG','TR?NG',100,100002,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('PHï¿½NG R?NG, CAO',30,'D??NG THï¿½NH GIï¿½NG,PH??NG T?NG NH?N,QU?N TH? ??C,HCMC',2500000,'PHï¿½NG ?ï¿½Y ?? TI?N NGHI','TR?NG',200,100003,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('NHï¿½ R?NG Rï¿½I',40,'???NG 5, PH??NG DAKAO,QU?N 1,HCMC',5000000,'NHï¿½ R?NG, M?T PH? GIï¿½P 2 CON ???NG','TR?NG',100,100004,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('PHï¿½NG S?CH, M?I',40,'???NG V?NH C?U NGHIï¿½NN,PH??NG A,QU?N TH? ??C,HCMC',2500000,'S?CH, TI?N NGHI, THOï¿½NG Mï¿½T','TR?NG',300,100005,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('PHï¿½NNG M?I Xï¿½Y THOï¿½NG Mï¿½T',30,'220 Tr?n Nï¿½o, P.An Khï¿½nh, TP.Th? ??c (Qu?n 2),HCMC',2000000,'??P','TR?NG',100,100006,0,'Cï¿½');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('CHO THUï¿½ PHï¿½NG',20,'27, Nguy?n Trung Tr?c, Qu?n 1, TP.HCM',2500000,'Thu?n l?i ?i l?i cho cï¿½c qu?n ( Bï¿½nh Th?nh, Th? ??c, Q.12,Tï¿½n Bï¿½nh','TR?NG',300,100007,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('phï¿½ng ??y ?? ti?n nghi.',15,'235 Nguy?n V?n C?, P.Nguy?n C? Trinh, Qu?n 1, TP.HCM',2500000,'Cï¿½ mï¿½y l?nh,n?m,t? qu?n ï¿½o,k? b?p','TR?NG',300,100008,0,'KHï¿½NG');
INSERT INTO ROOM (NAME,AREA,LOCATION,PRICE,DESCRIPTION,STATUS,CATEGORYID,LANDLORDCONTRACTID,VOTE,ISALLOWMATCH) VALUES('phï¿½ng ??p, r?ng',40,'410B Nguy?n Th? Minh Khai,P.5, Qu?n 3,HCM',2500000,'Cï¿½ b?o v? gi? xe, camera ??m b?o cho tï¿½i s?n b?n ???c an toï¿½n tuy?t ??i.','TR?NG',400,100009,0,'KHï¿½NG');
INSERT INTO ROOMCATEGORYDETAIL VALUES (100,1);
INSERT INTO ROOMCATEGORYDETAIL VALUES (200,2);
INSERT INTO ROOMCATEGORYDETAIL VALUES (300,3);
INSERT INTO ROOMCATEGORYDETAIL VALUES (400,4);
INSERT INTO ROOMCATEGORYDETAIL VALUES (500,5);
INSERT INTO ROOMCATEGORYDETAIL VALUES (600,0);

INSERT INTO CUSTOMER VALUES(839457201634, 'NGUY?N ?ï¿½NH HUï¿½N','0123456789','NAM','15-APR-88','0458712','NGUY?N DC','0890123456',NULL);
INSERT INTO CUSTOMER VALUES(562910384725, 'NGUY?N V?N THANH','0987654321','NAM','22-SEP-95','0983654','NGUY?N Sï¿½','0456789012',NULL);
INSERT INTO CUSTOMER VALUES(471829065318, 'TR?N DUY H?NG','0345678901','NAM','03-NOV-81','0128765','TR?N Bï¿½CH NG?C','0789012345',NULL);
INSERT INTO CUSTOMER VALUES(203956874102, 'D??NG THï¿½Y LINH','0567890123','N?','07-JUN-94','0321876','D??NG DUY LINH','0678901234',NULL);
INSERT INTO CUSTOMER VALUES(785639210347, 'TR?N HOï¿½I VY','0876543210','N?','28-DEC-90','0897543','NGUY?N DH','0129876543',NULL);

INSERT INTO LANDLORD VALUES (456789012345, 'NGUY?N MINH NGUYï¿½N','0861233455','1234234');

INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');
INSERT INTO CONTRACT_LANDLORD (LANDLORDID,SIGNED_DATE,STATUS) VALUES (456789012345,'28-DEC-2015','?ï¿½ DUY?T');


INSERT INTO ACCOUNT VALUES('0123456789', 'NGUY?N ?ï¿½NH HUï¿½N','CUSTOMER','HUAN@GMAIL.COM','1234');
INSERT INTO ACCOUNT VALUES('0987654321', 'THANH NV','CUSTOMER','THANH@GMAIL.COM','1234');
INSERT INTO ACCOUNT VALUES('0345678901', 'TR?N DUY H?NG','CUSTOMER','GAY@GMAIL.COM','1234');
INSERT INTO ACCOUNT VALUES('0567890123', 'LINH MIU','CUSTOMER','MIU@GMAIL.COM','1234');
INSERT INTO ACCOUNT VALUES('0876543210', 'VYEY','CUSTOMER','VYE@GMAIL.COM','1234');


INSERT INTO CONTRACT(CUSTOMER_ID,CUSTOMER_NAME,ROOM_ID,DURATION,PRICE,SIGN_DATE,STATUS,ELECTRICPRICE,WATERPRICE,ENTER_DATE,CANCEL_DATE,DEPOSIT,NUMBEROFPEOPLE) VALUES (839457201634,'NGUY?N ?ï¿½NH HUï¿½N',1018,6,2500000,'05-APR-22','?ï¿½ DUY?T',3500,6000,'05-APR-22',NULL,2500000,1);
INSERT INTO CONTRACT (CUSTOMER_ID,CUSTOMER_NAME,ROOM_ID,DURATION,PRICE,SIGN_DATE,STATUS,ELECTRICPRICE,WATERPRICE,ENTER_DATE,CANCEL_DATE,DEPOSIT,NUMBEROFPEOPLE) VALUES (562910384725,'NGUY?N V?N THANH',1019,6,3000000,'15-JUN-21','?ï¿½ DUY?T',3500,6000,'15-JUN-21',NULL,3000000,2);
INSERT INTO CONTRACT (CUSTOMER_ID,CUSTOMER_NAME,ROOM_ID,DURATION,PRICE,SIGN_DATE,STATUS,ELECTRICPRICE,WATERPRICE,ENTER_DATE,CANCEL_DATE,DEPOSIT,NUMBEROFPEOPLE) VALUES (471829065318,'TR?N DUY H?NG',1020,12,1500000,'23-DEC-20','CH? DUY?T',3500,6000,'23-DEC-20',NULL,1500000,3);


INSERT INTO CUSTOMER_LANDLORD_PROFILE VALUES(839457201634,'src/icon/PROFILE_IMAGE/PR0E4.jpg');
INSERT INTO CUSTOMER_LANDLORD_PROFILE VALUES(562910384725,'src/icon/PROFILE_IMAGE/PR01.jpg');
INSERT INTO CUSTOMER_LANDLORD_PROFILE VALUES(471829065318,'src/icon/PROFILE_IMAGE/PR02.jpg');
INSERT INTO CUSTOMER_LANDLORD_PROFILE VALUES(203956874102,'src/icon/PROFILE_IMAGE/PR03.jpg');
INSERT INTO CUSTOMER_LANDLORD_PROFILE VALUES(785639210347,'src/icon/PROFILE_IMAGE/PR06.jpg');

SELECT * FROM ROOM;
INSERT INTO ROOMIMAGE VALUES(1018,'icon/ROOM_IMAGE/NHA01.jpg');
INSERT INTO ROOMIMAGE VALUES(1019,'icon/ROOM_IMAGE/NHA02.jpg');
INSERT INTO ROOMIMAGE VALUES(1020,'icon/ROOM_IMAGE/NHA03.jpg');
INSERT INTO ROOMIMAGE VALUES(1021,'icon/ROOM_IMAGE/NHA04.jpg');
INSERT INTO ROOMIMAGE VALUES(1022,'icon/ROOM_IMAGE/NHA05.jpg');
INSERT INTO ROOMIMAGE VALUES(1023,'icon/ROOM_IMAGE/NHA06.jpg');
INSERT INTO ROOMIMAGE VALUES(1024,'icon/ROOM_IMAGE/NHA07.webp');
INSERT INTO ROOMIMAGE VALUES(1025,'icon/ROOM_IMAGE/NHA08.jpg');
INSERT INTO ROOMIMAGE VALUES(1026,'icon/ROOM_IMAGE/NHA10.jpg');
INSERT INTO ROOMIMAGE VALUES(1018,'icon/ROOM_IMAGE/NHA09.jpg');


INSERT INTO REVIEWROOM VALUES(1001,839457201634,'T?T, R?NG Rï¿½I',5);
INSERT INTO REVIEWROOM VALUES(1002,562910384725,'GIï¿½ C? PH?I CH?NG',4);
INSERT INTO REVIEWROOM VALUES(1003,471829065318,'Cï¿½N NHI?U B?T TI?N',3);
INSERT INTO REVIEWROOM VALUES(1004,203956874102,'KHï¿½NG GIAN THOï¿½NG Mï¿½T, THï¿½N THI?N',5);
INSERT INTO REVIEWROOM VALUES(1005,785639210347,'D? TH??NG, ??P',5);
INSERT INTO REVIEWROOM VALUES(1006,NULL,NULL,NULL);
INSERT INTO REVIEWROOM VALUES(1007,NULL,NULL,NULL);
INSERT INTO REVIEWROOM VALUES(1008,NULL,NULL,NULL);
INSERT INTO REVIEWROOM VALUES(1009,NULL,NULL,NULL);
INSERT INTO REVIEWROOM VALUES(1010,NULL,NULL,NULL);


INSERT INTO RESIDENT_REGISTRATION VALUES(839457201634,'??NG NAI','???NG TR?N,PH??NG 2,QU?N 3,HCMC','???NG TR?N,PH??NG 2,QU?N 3,HCMC','SINH VIï¿½N');
INSERT INTO RESIDENT_REGISTRATION VALUES(562910384725,'TP.VINH','???NG TR?N H?NG ??O,PH??NG 5,QU?N 1,HCMC','???NG TR?N H?NG ??O,PH??NG 5,QU?N 1,HCMC','K? S? INTEL');
INSERT INTO RESIDENT_REGISTRATION VALUES(471829065318,'?ï¿½ N?NG','???NG Vï¿½ TH? Sï¿½U,PH??NG 4,QU?N 5,HCMC','???NG Vï¿½ TH? Sï¿½U,PH??NG 4,QU?N 5,HCMC','SINH VIï¿½N');
INSERT INTO RESIDENT_REGISTRATION VALUES(203956874102,'Hï¿½ N?I','???NG THï¿½NH GIï¿½NG,PH??NG T?NG NH?N,QU?N TH? ??C,HCMC','???NG THï¿½NH GIï¿½NG,PH??NG T?NG NH?N,QU?N TH? ??C,HCMC','KINH DOANH');
INSERT INTO RESIDENT_REGISTRATION VALUES(785639210347,'KHï¿½NH Hï¿½A','???NG DA,PH??NG DAKAO,QU?N 1,HCMC','???NG DA,PH??NG DAKAO,QU?N 1,HCMC','SINH VIï¿½N');

INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (839457201634,'30-MAY-24', '31-MAY-24','?ï¿½ THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (562910384725,'30-FEB-24', '31-MAY-24','CH?A THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (471829065318,'30-JAN-24', '31-MAY-24','?ï¿½ THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (203956874102,'30-JUN-24', '31-MAY-24','?ï¿½ THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (839457201634,'30-MAY-24', '31-MAY-24','CH?A THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (839457201634,'30-APR-24', '31-MAY-24','?ï¿½ THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (785639210347,'30-APR-24', '31-MAY-24','CH?A THANH TOï¿½N');
INSERT INTO BILL (CUSTOMER_ID,DATE_CREATED,PAY_DATE,STATUS) VALUES (456789012345,'11-JAN-24','11-JAN-24','?ï¿½ THANH TOï¿½N');


INSERT INTO BILL_CUSTOMER VALUES(10,10,50,30000,30000,);
INSERT INTO BILL_CUSTOMER VALUES(11,10,50,30,30,250000);
INSERT INTO BILL_CUSTOMER VALUES(12,10,50,30,30,1500000);
INSERT INTO BILL_CUSTOMER VALUES(13,10,50,30,30,1000000);
INSERT INTO BILL_CUSTOMER VALUES(14,10,50,30,30,2300000);
INSERT INTO BILL_CUSTOMER VALUES(15,10,50,30,30,2300000);
INSERT INTO BILL_CUSTOMER VALUES(16,10,50,30,30,2300000);


INSERT INTO BILL_LANDLORD VALUES(18,98765,100000);

ALTER TABLE ROOM ADD CONSTRAINT PK_ROOM PRIMARY KEY (ROOMID) ENABLE;
ALTER TABLE ROOMCATEGORYDETAIL ADD CONSTRAINT PK_ROOMCATEGORY PRIMARY KEY (CATEGORYID) ENABLE;
ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (PHONE) ENABLE;
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CCCD) ENABLE;
ALTER TABLE LANDLORD ADD CONSTRAINT PK_LANDLORD PRIMARY KEY (CCCD) ENABLE;
ALTER TABLE CONTRACT ADD CONSTRAINT PK_CONTRACT PRIMARY KEY (CONTRACTID) ENABLE;
ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMP PRIMARY KEY (EMPLOYEE_ID) ENABLE;
ALTER TABLE BILL ADD CONSTRAINT PK_BILL PRIMARY KEY (BILL_ID) ENABLE;
ALTER TABLE BILL_LANDLORD ADD CONSTRAINT PK_BILL_LANDLORD PRIMARY KEY (BILL_ID) ENABLE;
ALTER TABLE BILL_CUSTOMER ADD CONSTRAINT PK_BILL_CUSTOMER PRIMARY KEY (BILL_ID) ENABLE;
ALTER TABLE ROOMSERVICE ADD CONSTRAINT PK_BILL_SERVICES PRIMARY KEY (SERVICE_ID) ENABLE;
ALTER TABLE RESIDENT_REGISTRATION ADD CONSTRAINT PK_BILL_RES PRIMARY KEY (CCCD) ENABLE;
ALTER TABLE CONTRACT_LANDLORD ADD CONSTRAINT PK_CONTRACT_LANDLORD PRIMARY KEY (CONTRACTID) ENABLE;


ALTER TABLE ROOM ADD CONSTRAINT FK_ROOMDETAIL FOREIGN KEY (CATEGORYID) REFERENCES ROOMCATEGORYDETAIL (CATEGORYID) ENABLE;
ALTER TABLE REVIEWROOM ADD CONSTRAINT FK_REVIEWROOM FOREIGN KEY (ROOMID) REFERENCES ROOM (ROOMID) ENABLE;
ALTER TABLE ROOM ADD CONSTRAINT FK_LANDLORD_CONTRACTID FOREIGN KEY (LANDLORDCONTRACTID) REFERENCES CONTRACT_LANDLORD(CONTRACTID) ON DELETE CASCADE ENABLE;
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_ACC_CUS FOREIGN KEY (PHONE) REFERENCES ACCOUNT(PHONE) ENABLE;
ALTER TABLE CONTRACT_LANDLORD ADD CONSTRAINT FK_CONTRACT_LANLORD FOREIGN KEY (LANDLORDID) REFERENCES LANDLORD(CCCD) ENABLE;
ALTER TABLE CONTRACT ADD CONSTRAINT FK_CON_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOMID) ENABLE;
ALTER TABLE CONTRACT ADD CONSTRAINT FK_CON_CUS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CCCD) ENABLE;
ALTER TABLE BILL_LANDLORD ADD CONSTRAINT FK_BILL_LL FOREIGN KEY (BILL_ID) REFERENCES BILL (BILL_ID) ENABLE;
ALTER TABLE BILL_CUSTOMER ADD CONSTRAINT FK_BILL_CUS FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID) ENABLE;   
ALTER TABLE BILL_LANDLORD ADD CONSTRAINT FK_BILL_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT_LANDLORD(CONTRACTID) ENABLE;

ALTER TABLE ROOMSERVICE ADD CONSTRAINT FK_SER_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOMID) ENABLE;
ALTER TABLE RESIDENT_REGISTRATION ADD CONSTRAINT FK_RES_CUS FOREIGN KEY (CCCD) REFERENCES CUSTOMER(CCCD) ENABLE; 
ALTER TABLE REVIEWROOM ADD CONSTRAINT FK_REV_CUS FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CCCD) ENABLE;
ALTER TABLE REVIEWROOM ADD CONSTRAINT FK_REV_ROOM FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID) ENABLE;
ALTER TABLE REPORTCUSTOMER ADD CONSTRAINT FK_RP_ROOMID FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID) ENABLE;
ALTER TABLE REPORTCUSTOMER ADD CONSTRAINT FK_RP_CUSROOT FOREIGN KEY (FROM_CUSTOMER) REFERENCES CUSTOMER(CCCD) ENABLE;
ALTER TABLE LANDLORD ADD CONSTRAINT FK_ACC_LAN FOREIGN KEY (PHONE) REFERENCES ACCOUNT(PHONE) ENABLE;

CREATE OR REPLACE PROCEDURE CNTROOMVOTE
(ROOM_ID IN NUMBER)
IS
  SUM_VOTE NUMBER;
BEGIN
   SELECT SUM(VOTE)/COUNT(VOTE) INTO SUM_VOTE FROM REVIEWROOM WHERE ROOMID=ROOM_ID;
   UPDATE ROOM SET VOTE=SUM_VOTE WHERE ROOM.ROOMID=ROOM_ID;
END;


commit;