/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Room;
import view.CustomControl.TableCellAction2;
import view.CustomControl.tablecellRenderFor3item;

/**
 *
 * @author Admin
 */
public class RoomManage extends javax.swing.JPanel {
    private final DefaultTableModel tableModel;
    private final TableRowSorter sorter;
    /**
     * Creates new form RoomManage
     */
    public RoomManage() {
        initComponents();
        txtFilter.setLabelText("Tìm kiếm phòng");
        tableModel = (DefaultTableModel) table.getModel();
        sorter = new TableRowSorter<>(tableModel);
        txtFilter.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                 initFilter();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                initFilter();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
         }
        });
        table.setRowSorter(sorter);
    }
    public void initTable(ArrayList<Room> list){
        table.getColumnModel().getColumn(4).setCellRenderer(new tablecellRenderFor3item("icon/showcontract.svg icon/delete.svg icon/detail3.svg"));
        tableModel.setRowCount(0);
        for(Room room : list){
            tableModel.addRow(new Object[]{"#"+room.getID(),room.getName(),room.getPrices(),room.getStatus()});
        }
        table.setModel(tableModel);
    }
     private void initFilter(){
        RowFilter<DefaultTableModel,Object> rowFilter = null;
        try{
            rowFilter = RowFilter.regexFilter(txtFilter.getText(), 1);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorter.setRowFilter(rowFilter);
    }
    public int getSelectionIndex(){
        return table.convertRowIndexToModel(table.getSelectedRow());
    }
    public void setActionListenerFortablebtn(ActionListener listener, ActionListener listener1,ActionListener listener2){
         table.getColumnModel().getColumn(4).setCellEditor(new TableCellAction2(listener,listener1,listener2, "icon/showcontract.svg icon/delete.svg icon/detail3.svg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtFilter = new view.CustomControl.TextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Quản lý phòng ở");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tên phòng", "Giá", "Trạng thái", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(50);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private view.CustomControl.TextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
