/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Room;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import view.CustomControl.StyledButtonUI;
import view.CustomControl.CustomScrollBarUI;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import model.Room;

/**
 *
 * @author Admin
 */
public class Post_Form extends javax.swing.JPanel {
    public DefaultListModel<Room> defaultListModel;
    public final String[] listLocation = {"Tất cả","Quận 1","Quận 2","Quận 3","Quận 4","Quận 5","Quận 6","Quận 7","Quận 8"
,"Quận 10"
,"Quận 11"
,"Quận 12"
,"Quận Tân Bình"
,"Quận Bình Tân"
,"Quận Bình Thạnh"
,"Quận Tân Phú"
,"Quận Gò Vấp"
,"Quận Phú Nhuận"};
    public final String[] listCategory = {"Tất cả"
,"Phòng 1 người"
,"Phòng 2 người"
,"Phòng 3 người"
,"Phòng 4 người"
,"Phòng 5 người"
,"Phòng ngắn hạn"};
    /**
     * Creates new form Post_Form
     */
    public Post_Form() {
        initComponents();
        CustomButtonCode();
        cmbLocation.setModel(new DefaultComboBoxModel(listLocation));
        cmbCategory.setModel(new DefaultComboBoxModel(listCategory));
        cmbLocation.setLabeText("Địa chỉ");
        cmbCategory.setLabeText("Loại phòng");
        cmbCategory.setSelectedIndex(0);
        cmbLocation.setSelectedIndex(0);
    }
    public void initList(List<Room> list)
    {
        defaultListModel = new DefaultListModel<>();
        for(Room room : list)
        {
            defaultListModel.addElement(room);
        }
        jList1.setModel(defaultListModel);
        jList1.setCellRenderer(new RoomItemView());
    }
    public void setActionListenerforlbl2M(ActionListener listener)
    {
        btnLower2M.addActionListener(listener);
    }
    public void setActionListenerforlbl2to4(ActionListener listener)
    {
        btn2to4.addActionListener(listener);
    }
    public void setActionListenerforlbl4to7(ActionListener listener)
    {
        btn4to7.addActionListener(listener);
    }
    public void setActionListnerforlbl7(ActionListener listener)
    {
        btn7.addActionListener(listener);
    }
    public void setActionListenerforlblAllPrice(ActionListener listener)
    {
        btnAllPrice.addActionListener(listener);
    }
    public void setMouseEventForJlist(MouseListener listener)
    {
        jList1.addMouseListener(listener);
    }
    public int getIndexofSelectedItem()
    {
        return jList1.getSelectedIndex();
    }
    public void addToFilter(String filterString)
    {
        JButton newButton = new JButton(filterString);
        newButton.setUI(new StyledButtonUI());
        newButton.setBackground(new Color(0,204,0));
        newButton.setForeground(Color.WHITE);
        newButton.setFont(new Font("Cascadia Code",Font.PLAIN,12));
        newButton.addActionListener(new ActionListener()
                {
            @Override
            public void actionPerformed(ActionEvent e) {
                filter.remove(newButton);
                filter.repaint();
                filter.revalidate();
            }
        });
        filter.add(newButton);
        repaint();
        revalidate();
    }
    public void initOverviewData(int[] arr)
    {
        lblPhongTrong.setText(String.valueOf(arr[0]));
        lblMatch_Room.setText(String.valueOf(arr[1]));
        lblShortTerm.setText(String.valueOf(arr[2]));
    }
    public int getSelectedCmbLocation(){
        return cmbLocation.getSelectedIndex();
    }
    public int getSelectedcmbCategory(){
        return cmbLocation.getSelectedIndex();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        emptyRoom1 = new view.Room.EmptyRoom();
        lblPhongTrong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        matchRoom1 = new view.Room.MatchRoom();
        lblMatch_Room = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        shortTermRoom1 = new view.Room.ShortTermRoom();
        lblShortTerm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        btnAllPrice = new javax.swing.JButton();
        btnLower2M = new javax.swing.JButton();
        btn2to4 = new javax.swing.JButton();
        btn4to7 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmbLocation = new view.CustomControl.Combobox();
        cmbCategory = new view.CustomControl.Combobox();
        filter = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.GridLayout(0, 3, 5, 0));

        lblPhongTrong.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblPhongTrong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhongTrong.setText("NULL");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phòng Trống");

        javax.swing.GroupLayout emptyRoom1Layout = new javax.swing.GroupLayout(emptyRoom1);
        emptyRoom1.setLayout(emptyRoom1Layout);
        emptyRoom1Layout.setHorizontalGroup(
            emptyRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emptyRoom1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(emptyRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        emptyRoom1Layout.setVerticalGroup(
            emptyRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emptyRoom1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblPhongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        jLayeredPane1.add(emptyRoom1);

        lblMatch_Room.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblMatch_Room.setForeground(new java.awt.Color(255, 255, 255));
        lblMatch_Room.setText("NULL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phòng cần ghép");

        javax.swing.GroupLayout matchRoom1Layout = new javax.swing.GroupLayout(matchRoom1);
        matchRoom1.setLayout(matchRoom1Layout);
        matchRoom1Layout.setHorizontalGroup(
            matchRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchRoom1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(matchRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblMatch_Room, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        matchRoom1Layout.setVerticalGroup(
            matchRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchRoom1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblMatch_Room, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLayeredPane1.add(matchRoom1);

        lblShortTerm.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblShortTerm.setForeground(new java.awt.Color(255, 255, 255));
        lblShortTerm.setText("NULL");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phòng ngắn hạn");

        javax.swing.GroupLayout shortTermRoom1Layout = new javax.swing.GroupLayout(shortTermRoom1);
        shortTermRoom1.setLayout(shortTermRoom1Layout);
        shortTermRoom1Layout.setHorizontalGroup(
            shortTermRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shortTermRoom1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(shortTermRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblShortTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        shortTermRoom1Layout.setVerticalGroup(
            shortTermRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shortTermRoom1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblShortTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLayeredPane1.add(shortTermRoom1);

        jLayeredPane2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(268, 500));

        jList1.setBorder(null);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane1.setViewportView(jList1);

        jLayeredPane2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 432));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setRequestFocusEnabled(false);

        jLayeredPane3.setBackground(new java.awt.Color(0, 102, 255));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setPreferredSize(new java.awt.Dimension(175, 31));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lọc theo giá");

        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAllPrice.setBackground(new java.awt.Color(0, 204, 0));
        btnAllPrice.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        btnAllPrice.setForeground(new java.awt.Color(255, 255, 255));
        btnAllPrice.setText("Tất cả");

        btnLower2M.setBackground(new java.awt.Color(0, 204, 0));
        btnLower2M.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        btnLower2M.setForeground(new java.awt.Color(255, 255, 255));
        btnLower2M.setText("Dưới 2 triệu");
        btnLower2M.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn2to4.setBackground(new java.awt.Color(0, 204, 0));
        btn2to4.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        btn2to4.setForeground(new java.awt.Color(255, 255, 255));
        btn2to4.setText("Từ 2 - 4 triệu");

        btn4to7.setBackground(new java.awt.Color(0, 204, 0));
        btn4to7.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        btn4to7.setForeground(new java.awt.Color(255, 255, 255));
        btn4to7.setText("Từ 4-7 triệu");

        btn7.setBackground(new java.awt.Color(0, 204, 0));
        btn7.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("Trên 7 triệu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAllPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7)
                    .addComponent(btn4to7)
                    .addComponent(btn2to4)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLower2M, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLower2M)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btn2to4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4to7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn7)
                .addGap(3, 3, 3))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        filter.setBackground(new java.awt.Color(255, 255, 255));
        filter.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(filter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filter, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jLayeredPane2.add(jPanel1, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void CustomButtonCode()
    {
        btn2to4.setUI(new StyledButtonUI());
        btn4to7.setUI(new StyledButtonUI());
        btn7.setUI(new StyledButtonUI());
        btnAllPrice.setUI(new StyledButtonUI());
        btnLower2M.setUI(new StyledButtonUI());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2to4;
    private javax.swing.JButton btn4to7;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btnAllPrice;
    private javax.swing.JButton btnLower2M;
    private view.CustomControl.Combobox cmbCategory;
    private view.CustomControl.Combobox cmbLocation;
    private view.Room.EmptyRoom emptyRoom1;
    private javax.swing.JPanel filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JList<Room> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMatch_Room;
    private javax.swing.JLabel lblPhongTrong;
    private javax.swing.JLabel lblShortTerm;
    private view.Room.MatchRoom matchRoom1;
    private view.Room.ShortTermRoom shortTermRoom1;
    // End of variables declaration//GEN-END:variables
}
