/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import java.awt.event.ActionListener;
import javax.swing.JComponent;

/**
 *
 * @author Admin
 */
public class MainMonitor extends javax.swing.JFrame {
    /**
     * Creates new form MainMonitor
     */
    public MainMonitor() {
        initComponents();
    }
    public void setForm (JComponent com)
    {
           jPanel1.removeAll();
           jPanel1.add(com);
           jPanel1.repaint();
           jPanel1.revalidate();
    }
    public void setActionListenerForlblPostForm(ActionListener listener)
    {
         btnPost.addActionListener(listener);
    }
    public void setActionListenerForlblContract (ActionListener listener)
    {
        btnContract.addActionListener(listener);
    }
    public void setActionListenerForbtnInfo(ActionListener listener)
    {
        btninfo.addActionListener(listener);
    }
    public void setActionListenerForbtnLogout(ActionListener listener)
    {
        btnlogout.addActionListener(listener);
    }
    public void setActionListenerForbtnSearchMatch(ActionListener listener)
    {
        btnSearchMatch.addActionListener(listener);
    }
    public void setActionListenerForbtnRegistration(ActionListener listener){
        btnResident.addActionListener(listener);  
    }
    public void setActionListenerforBtnBill(ActionListener listener){
        btnBill.addActionListener(listener);
    }
    public void setActionListenerforBtnService(ActionListener listener){
        btnService.addActionListener(listener);
    }
    public void DisposeFrame()
    {
        this.setVisible(false);
        this.dispose();
    }
    public void setLandlordBtn(boolean state){
        btnLandLord.setVisible(state);
        this.repaint();
        this.revalidate();
    }
    public void setActionListenerforLandlordbtn(ActionListener listener){
        btnLandLord.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new view.Menu();
        jLabel1 = new javax.swing.JLabel();
        btnPost = new javax.swing.JButton();
        btnContract = new javax.swing.JButton();
        btninfo = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnSearchMatch = new javax.swing.JButton();
        btnService = new javax.swing.JButton();
        btnResident = new javax.swing.JButton();
        btnLandLord = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(900, 600));

        menu1.setPreferredSize(new java.awt.Dimension(200, 600));

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jLabel1.setText("Nhà Trọ");

        btnPost.setBackground(new java.awt.Color(51, 153, 255));
        btnPost.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnPost.setForeground(new java.awt.Color(255, 255, 255));
        btnPost.setText("Bài đăng");
        btnPost.setBorderPainted(false);
        btnPost.setContentAreaFilled(false);
        btnPost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPost.setPreferredSize(new java.awt.Dimension(100, 30));

        btnContract.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnContract.setForeground(new java.awt.Color(255, 255, 255));
        btnContract.setText("Hợp đồng");
        btnContract.setBorderPainted(false);
        btnContract.setContentAreaFilled(false);
        btnContract.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnContract.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnContract.setPreferredSize(new java.awt.Dimension(100, 30));

        btninfo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btninfo.setForeground(new java.awt.Color(255, 255, 255));
        btninfo.setText("Thông tin cá nhân");
        btninfo.setBorderPainted(false);
        btninfo.setContentAreaFilled(false);

        btnBill.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBill.setForeground(new java.awt.Color(255, 255, 255));
        btnBill.setText("Hóa Đơn");
        btnBill.setBorderPainted(false);
        btnBill.setContentAreaFilled(false);
        btnBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBill.setPreferredSize(new java.awt.Dimension(100, 30));

        btnSearchMatch.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSearchMatch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchMatch.setText("Tìm bạn ở ghép");
        btnSearchMatch.setBorderPainted(false);
        btnSearchMatch.setContentAreaFilled(false);
        btnSearchMatch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnService.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnService.setForeground(new java.awt.Color(255, 255, 255));
        btnService.setText("Dịch vụ");
        btnService.setBorderPainted(false);
        btnService.setContentAreaFilled(false);
        btnService.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnResident.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnResident.setForeground(new java.awt.Color(255, 255, 255));
        btnResident.setText("Đăng ký Tạm trú");
        btnResident.setBorderPainted(false);
        btnResident.setContentAreaFilled(false);
        btnResident.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnLandLord.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnLandLord.setForeground(new java.awt.Color(255, 255, 255));
        btnLandLord.setText("Chủ nhà");
        btnLandLord.setBorderPainted(false);
        btnLandLord.setContentAreaFilled(false);
        btnLandLord.setDefaultCapable(false);
        btnLandLord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Đăng xuất");
        btnlogout.setBorder(null);
        btnlogout.setBorderPainted(false);
        btnlogout.setContentAreaFilled(false);

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btninfo))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnResident))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnService, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchMatch))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnContract, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPost, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLandLord, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(btnPost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnContract, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSearchMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnResident, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLandLord)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(menu1, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnContract;
    private javax.swing.JButton btnLandLord;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnResident;
    private javax.swing.JButton btnSearchMatch;
    private javax.swing.JButton btnService;
    private javax.swing.JButton btninfo;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private view.Menu menu1;
    // End of variables declaration//GEN-END:variables
}
