/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class Welcompage extends javax.swing.JPanel {
    private BufferedImage img;
    private int currentWidth = 900;
    private int currentHeight = 600;
    public Welcompage() {
        initComponents();
        try 
        {
            img = ImageIO.read(new File("src/resource/welcompage.jpg"));
        }
        catch(IOException e)
        {
            System.out.println(e.getMessage());
        }
        addComponentListener(new ComponentAdapter(){
            @Override
            public void componentResized(ComponentEvent e) {
                currentWidth = e.getComponent().getWidth();
                currentHeight = e.getComponent().getHeight();
                repaint();
            }
        });
        addLabel();
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(img, 0, 0,currentWidth,currentHeight,this);
    }
    private void addLabel()
    {
        JLabel label = new JLabel("Welcome");
        try {
            File file = new File("src/resource/Sono-Regular.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, file).deriveFont(44f).deriveFont(Font.BOLD);
        label.setFont(font);
        label.setForeground(Color.WHITE);
        } catch (Exception e) {
        }
        this.add(label);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
