/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.User;

import java.awt.event.ActionListener;
import model.ContractDetail;
import model.ResidentDetail;
import view.CustomControl.CustomScrollBarUI;
import view.CustomControl.StyledButtonUI;

/**
 *
 * @author Admin
 */
public class ResidentRegistration extends javax.swing.JPanel {

    /**
     * Creates new form ResidentRegistration
     */
    public ResidentRegistration() {
        initComponents();
        initCustomUI();
    }
    private void initCustomUI(){
        txtCCCD.setLabelText("Số căn cước công dân");
        txtCurrent.setLabelText("Nơi ở hiện tại");
        txtTemp.setLabelText("Nơi ở tạm trú");
        txtPermanent.setLabelText("Nơi ở thường trú");
        txtWork.setLabelText("Công việc hiện tại");
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
    }
    public void RenderData(ResidentDetail data){
        if (data != null){
        txtCCCD.setText(String.valueOf(data.getCCCD()));
        txtCurrent.setText(String.valueOf(data.getCurrent_resident()));
        txtTemp.setText(String.valueOf(data.getTemporary_accommodation()));
        txtPermanent.setText(String.valueOf(data.getPermanent_resident()));
        txtWork.setText(String.valueOf(data.getCurrent_work()));
        }
    }
    public ResidentDetail UpdateData(){
        ResidentDetail data = new ResidentDetail();
        data.setCCCD(Long.valueOf(txtCCCD.getText()));
        data.setCurrent_work(String.valueOf(txtWork.getText()));
        data.setPermanent_resident(String.valueOf(txtPermanent.getText()));
        data.setCurrent_resident(String.valueOf(txtCurrent.getText()));
        data.setTemporary_accommodation(String.valueOf(txtTemp.getText()));
        return data;
    }
    public void setActionListenerForUpdateBtn(ActionListener listener){
        btnUpdate.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCCCD = new view.CustomControl.TextField();
        txtCurrent = new view.CustomControl.TextField();
        txtTemp = new view.CustomControl.TextField();
        txtPermanent = new view.CustomControl.TextField();
        txtWork = new view.CustomControl.TextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tờ Khai Đăng Ký Tạm Trú");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Câu Hỏi Thường Gặp");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Đăng Ký Tạm Trú Là Nghĩa Vụ Của Chủ Trọ Hay Người Thuê?\n\n- Chủ trọ sẽ là người chủ động liên hệ để đăng ký tạm trú cho khách thuê\n\nKhi Nào Tôi Cần Làm Thủ Tục Đăng Ký Tạm Trú Cho Người Ở Trọ?\n\n-Trong vòng 30 ngày bạn cần đăng ký tạm trú\n\nKhông Đăng Ký Tạm Trú Thì Sẽ Bị Xử Phạt Như Thế Nào?\n\n- Cá nhân hoặc chủ trọ không thực hiện đăng ký tạm trú hoặc điều chỉnh trong sổ Tạm trú bị phạt từ 100 – 300 nghìn đồng\n- Cá nhân hoặc chủ trọ cổ tình làm sai lệch nội dung Sổ tạm trú hoặc giấy tờ liên quan đến cư trú bị phạt từ 1 – 2 triệu đồng.\n- Cá nhân hoặc chủ trọ cố tình khai man hoặc giả mạo giấy tờ cư trú, Sổ cư trú sẽ bị phạt từ 2 – 4 triệu đồng.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnUpdate.setBackground(new java.awt.Color(0, 255, 51));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Cập Nhật");
        btnUpdate.setUI(new StyledButtonUI());
        jPanel1.add(btnUpdate, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPermanent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCurrent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtPermanent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 475, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private view.CustomControl.TextField txtCCCD;
    private view.CustomControl.TextField txtCurrent;
    private view.CustomControl.TextField txtPermanent;
    private view.CustomControl.TextField txtTemp;
    private view.CustomControl.TextField txtWork;
    // End of variables declaration//GEN-END:variables
}
