/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.CustomControl;

/**
 *
 * @author Admin
 */
public class PanelStar extends javax.swing.JPanel {

    /**
     * Creates new form PanelStar
     */
    public PanelStar() {
        initComponents();
        svgStar.setSVGImage("icon/star.svg", 20, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svgStar = new view.CustomControl.SVGimage();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
        add(svgStar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.CustomControl.SVGimage svgStar;
    // End of variables declaration//GEN-END:variables
}
